# server config
server:
  port: 8899
  servlet:
    context-path: /camera

spring:
  datasource:
    name: cameradb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/camera?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useAffectedRows=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: -1 # 不限制文件上传大小
      max-request-size: -1
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true
    time-zone: GMT+8

logging.level.com: debug
logging.file.name: E:/log/camera.log
logging.file.max-history: 20
logging.file.max-size: 20MB

app:
  filepath: D:/opt/camera

rtmp:
  rtmphost: 192.168.1.134:1935
  httphost: 192.168.1.134:8280